### ISSUE TITLE
I'm getting the same error on any sub-generator I choose, but not if I scaffold out the same ones individually

### ISSUE THREAD

**Issue by dewdad** [csantanapr/generator-dude#4]
I'm all done. Running npm install for you to install the required depende
unning the command yourself.

npm WARN package.json dude@0.0.0 No description
npm WARN package.json dude@0.0.0 No repository field.
Running Grunt

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

I'm using the latest version of everything -Node/NPM, Grunt, Bower

**Comment by csantanapr** [comment]
@randelic thanks for reporting the issue, I will take a look and let you know if I can reproduce

**Comment by csantanapr** [comment]
@randelic I was not able to replicate problem, but I updated the README with more clear instructions
https://github.com/csantanapr/generator-dude/blob/master/README.md

Here is what I tried using generator-webapp, let me know if you continue seing the problem and provide more debugging info.

$ npm install -g yo
$ npm install -g bower
$ npm install -g grunt-cli
$ npm install -g generator-dude
$ npm install -g generator-cordovacli

$ npm -v
1.3.21

$ node -v
v0.10.24

$ yo -v
1.1.2

$ bower -v
1.2.8

$ npm list -g grunt-cli
/Users/csantana23/.nvm/v0.10.24/lib
└──  grunt-cli@0.1.11

$ npm list -g generator-dude
/Users/csantana23/.nvm/v0.10.24/lib
└── generator-dude@0.1.7

$ npm list -g generator-cordovacli
/Users/csantana23/.nvm/v0.10.24/lib
└── generator-cordovacli@0.1.11

$ npm list -g generator-webapp
/Users/csantana23/.nvm/v0.10.24/lib
└── generator-webapp@0.4.6

$ mkdir test2
$ cd test2
test2:$ yo dude
[?] Must be already installed globally with npm install -g
Select a Web App Generator? generator-webapp        (github.com/yeoman/generator-webapp)
   create .editorconfig
   create package.json
   create Gruntfile.js
   create .gitignore
Running Generatorwebapp

```
 _-----_
|       |
|--(o)--|   .--------------------------.
```

   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /**_A**_\   '__________________________'
     |  ~  |
   **'._**.'__
 ´   `|° ´ Y`

Out of the box I include HTML5 Boilerplate and jQuery.
[?] What more would you like? Bootstrap for Sass, Modernizr
   create Gruntfile.js
   create package.json
   create .gitignore
   create .gitattributes
   create .bowerrc
   create bower.json
   create .jshintrc
   create .editorconfig
   create app/favicon.ico
   create app/404.html
   create app/robots.txt
   create app/.htaccess
   create app/styles/main.scss
   create app/index.html
   create app/scripts/main.js
   invoke   mocha:app
   create     test/bower.json
   create     test/.bowerrc
   create     test/spec/test.js
   create     test/index.html

I'm all done. Running bower install for you to install the required dependencies. If this fails, try running the command yourself.

bower cached        git://github.com/chaijs/chai.git#1.8.1
bower validate      1.8.1 against git://github.com/chaijs/chai.git#~1.8.0
bower cached        git://github.com/visionmedia/mocha.git#1.14.0
bower validate      1.14.0 against git://github.com/visionmedia/mocha.git#~1.14.0
bower install       chai#1.8.1
bower install       mocha#1.14.0

chai#1.8.1 bower_components/chai

mocha#1.14.0 bower_components/mocha
done with web generator
[?] What do you want to name your App? HelloCordova
[?] What do you want to name your Package ID? io.cordova.hellocordova
[?] What platforms would you like to add support for? Android, iOS
[?] What plugins would you like to add support for? Device
   create package.json
   create .editorconfig
   create .jshintrc
   create Gruntfile.js

I'm all done. Just run npm install to install the required dependencies.

**Comment by dewdad** [comment]
@csantanapr Firstly, let me saythank you for the prompt response and I think your work is awesome. I've already mentioned you to my team and promised a demo. Suddenly things are working quite as smoothly as they did before.

Ok, I did have to update node, npm and yo to match the versions you tested my versions are same as yours.

Here is what I'm getting on console, somehow cordova won't play nice (I'm running on Windows7 x64 if that matters).

PS C:\tmp\testdude> grunt cordova:prepare
Running "cordova:prepare" (cordova) task
setting cwd:./cordova
running grunt task :prepare
Running "cordovacli:prepare" (cordovacli) task

Using cordova CLI version (3.2.0-rc.1)

Setting Current Working Directory (CWD) to app

Running:node C:\tmp\testdude\cordova\node_modules\grunt-cordovacli\node_modules\cordova\bin\cordova prepare

> > Error: [Error: Current working directory is not a Cordova-based project.]

Warning: [Error: Current working directory is not a Cordova-based project.] Use --force to continue.

Aborted due to warnings.

Warning:  Use --force to continue.

**Comment by csantanapr** [comment]
@randelic I'm using OSX and doing Android and iOS with generator-webapp

It looks like there is a problem with grunt-cordovacli and the cordova CLI on Windows

As you can see I'm just running the Cordova CLI on the cordova/app directory.
I have a Windows 8 x64 VM, it should be similar I will give it a try

What is your specific use case so I can give it a try?
Android and generator-webapp?

**Comment by dewdad** [comment]
I am working with both the webapp generator at the polymer generator . In
both scenarios it seems like Cordova CLI is unable to create the Cordova
application. It seems that the grunt built step creates a WWW directory
inside the Cordova app directory and that causes the Cordova app creation
to fail.
