### ISSUE TITLE
JavaScript exception running generator

### ISSUE THREAD

**Issue by sauravg** [csantanapr/generator-dude#6]
tmp $ mkdir testapp
tmp $ cd testapp
testapp $ yo dude
[?] Must be already installed globally with npm install -g
Select a Web App Generator? generator-dapp          (github.com/csantanapr/generator-dapp)
   create .editorconfig
   create package.json
   create Gruntfile.js
   create .gitignore
Running Generatordapp
   create profiles/app.profile.js
   create src/app/config.json
   create src/app/controllers/CustomHistory.js
   create src/app/css/app.css
   create src/app/css/app_layout.css
   create src/app/css/app_theme.css
   create src/app/images/a-icon1.png
   create src/app/main.js
   create src/app/nls/app_strings.js
   create src/app/nls/es/app_strings.js
   create src/app/package.js
   create src/app/package.json
   create src/app/views/about/about.html
   create src/app/views/about/about.js
   create src/app/views/home/home.html
   create src/app/views/home/home.js
   create src/app/views/home/nls/es/home_strings.js
   create src/app/views/home/nls/home_strings.js
   create src/dist-index.html
   create src/index.html
   create .editorconfig
   create package.json
   create bower.json
   create Gruntfile.js
   create .bowerrc
   create .gitignore
   create LICENSE

I'm all done. Just run bower install & npm install to install the required dependencies.

done with web generator

/Users/sghosh/apps/npm/lib/node_modules/generator-dude/app/index.js:37
                genCordovaCLI = this.env.run('cordovacli',
                                    ^
TypeError: Cannot read property 'env' of undefined
    at /Users/sghosh/apps/npm/lib/node_modules/generator-dude/app/index.js:37:37
    at callback (/Users/sghosh/apps/npm/lib/node_modules/generator-dapp/node_modules/yeoman-generator/lib/base.js:315:5)
    at /Users/sghosh/apps/npm/lib/node_modules/generator-dapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13
    at async.eachSeries (/Users/sghosh/apps/npm/lib/node_modules/generator-dapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:130:20)
    at _asyncMap (/Users/sghosh/apps/npm/lib/node_modules/generator-dapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:226:9)
    at Object.mapSeries (/Users/sghosh/apps/npm/lib/node_modules/generator-dapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:216:23)
    at Object.async.series (/Users/sghosh/apps/npm/lib/node_modules/generator-dapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:549:19)
    at DappGenerator.runHooks (/Users/sghosh/apps/npm/lib/node_modules/generator-dapp/node_modules/yeoman-generator/lib/base.js:329:9)
    at runHooks (/Users/sghosh/apps/npm/lib/node_modules/generator-dapp/node_modules/yeoman-generator/lib/base.js:248:10)
    at /Users/sghosh/apps/npm/lib/node_modules/generator-dapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13

testapp $ cordova --version
3.4.1-0.1.0
testapp $ npm --version
1.4.3
testapp $ node --version
v0.10.26
testapp $ ls ~/.npm/generator-dude
0.1.8
testapp $ yo -v
1.2.0
testapp $

**Comment by nsharrok** [comment]
I get this error too in IOX

**Comment by nsharrok** [comment]
I'm also getting same error on windows 7
....
I'm all done. Just run bower install & npm install to install the required dependencies.
done with web generator
C:\Users\nsharrok.GVBH\AppData\Roaming\npm\node_modules\generator-dude\app\index.js:37
                genCordovaCLI = this.env.run('cordovacli',
                                    ^
TypeError: Cannot read property 'env' of undefined
....

**Comment by nsharrok** [comment]
OK fixed the issue:
in path to ...\npm\node_modules\generator-dude\app\index.js
I replaced 'this' in line 36 
                genCordovaCLI = this.env.run('cordovacli',

with 'genDude'
                genCordovaCLI = genDude.env.run('cordovacli',
Works as it should now

**Comment by SebastianTroc** [comment]
Don't you have intention to merge this to master?
